### ISSUE TITLE
Navigation bar bug

### ISSUE THREAD

**Issue by ivyhzyb** [miacheng2/CITS5206-capstone#79]
It's hard to identify the title of the selected page
![image](https://github.com/user-attachments/assets/771df14a-9606-411d-9689-909d09494024)

**Comment by miacheng2** [comment]
I have solved this problem.
![image](https://github.com/user-attachments/assets/ead15da7-aeb1-4851-8127-e037aa087108)
![WeChat5d09e6671e84083d77c66cce7f949f7b](https://github.com/user-attachments/assets/ab7401fd-7a1e-4d89-afab-5f1d94acccca)
